# Use postgres/example user/password credentials
version: '3.1'

services:

  odoo_14_web:
    image: odoo:14.0-prod
    restart: always
    depends_on:
      - igo_14_db
      - igo_14_redis
    ports:
      - 8069:8069
    environment:
      REDIS: igo_14_redis
      HOST: igo_14_db
      USER: igo_test_user
      PASSWORD: "1qazXSW3edcVFR"
      db-filter: odoo_db_.*
    volumes:
      - /home/ferren/Projects/odoo:/opt/odoo
      - /home/ferren/Projects/odoo-addons:/mnt/extra-addons
      - /home/ferren/DataStore/odoo-14/files:/var/lib/odoo
      - /home/ferren/DataStore/odoo-14/logs:/var/log/odoo
      - /home/ferren/DataStore/odoo-14/config:/etc/odoo
    networks:
      - odoo-net

  igo_14_db:
    image: postgres:13
    restart: always
    volumes:
      - /home/ferren/DataStore/odoo-14/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: igo_test_user
      POSTGRES_PASSWORD: "1qazXSW3edcVFR"
      POSTGRES_DB: postgres
    networks:
      - odoo-net

  igo_14_redis:
    image: redis
    restart: always
    volumes:
      - /home/ferren/DataStore/igo_14_redis:/data
    networks:
      - odoo-net

networks:
  odoo-net:
